<?php

/**
 * @file
 * Contains ppoship_module.module.
 * @author Hoang Phan <ace@hoangphan.tech>
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ppoship_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ppoship_module module.
    case 'help.page.ppoship_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('PPOSHIP Drupal 9 Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ppoship_module_theme() {
  return [
    'ppoship_module' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ppoship_module_preprocess_block(&$variables)
{
  // Alter block block-ppoship-theme-site-branding
  if (isset($variables['elements']['#id']) && $variables['elements']['#id'] === 'ppoship_theme_site_branding') {
    $variables['attributes']['class'][] = 'logo';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ppoship_module_preprocess_node__article__teaser(&$variables)
{
  $articleTeaserContent = &$variables['content'];
  $tmpImage = $variables['content']['field_image'];
  $tmpDescription = $variables['content']['body'];
  unset($variables['content']['field_image']);
  unset($variables['content']['body']);

  $articleTeaserContent['divImage'] = [
    '#prefix' => '<div class="img">',
    '#suffix' => '</div>',
    '#weight' => -100,
    'wrap' => [
      '#prefix' => '<div class="wrap" itemprop="image">',
      '#suffix' => '</div>',
      'image' => $tmpImage
    ]
  ];
  $articleTeaserContent['divCaption'] = [
    '#prefix' => '<div class="caption">',
    '#suffix' => '</div>',
    '#weight' => -95,
    'divTend' => [
      '#prefix' => '<div class="tend">',
      '#suffix' => '</div>',
      'headline' => [
        '#prefix' => '<h3 itemprop="headline">',
        '#suffix' => '</h3>',
        'link' => [
          '#prefix' => '<a itemprop="url" href="' . $variables['url'] . '">',
          '#suffix' => '</a>',
          '#markup' => $variables['label'][0]['#context']['value']
        ]
      ]
    ],
    'divDate' => [
      '#prefix' => '<div class="date">',
      '#suffix' => '</div>',
      '#markup' => $variables['date']
    ],
    'description' => [
      '#prefix' => '<div class="des" itemprop="description">',
      '#suffix' => '</div>',
      'content' => $tmpDescription
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ppoship_module_preprocess_form_element_label(&$variables)
{
  if (isset($variables['element']['#id']) && $variables['element']['#id']==='edit-field-news-type-target-id') {
    $variables['attributes']['class'][] = 'hide';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ppoship_module_preprocess_select(&$variables)
{
  if (isset($variables['attributes']['name']) && $variables['attributes']['name']==='field_news_type_target_id') {
    $variables['attributes']['class'][] = 'hide';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ppoship_module_preprocess_input__submit(&$variables)
{
  if(isset($variables['element']['#id']) && $variables['element']['#id'] ==='edit-submit-plp') {
    $variables['attributes']['class'][] = 'hide';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ppoship_module_preprocess_field(&$variables)
{
  // Custom display of field link_2youtube
  if (isset($variables['field_name']) && $variables['field_name'] === 'field_link_2youtube') {
    if (isset($variables['items'][0])) {
      $item =  $variables['items'][0];
      $youtubeLink = $item['content']['#title'];
      $variables['items'][0]['content'] = [
        '#markup' => $youtubeLink
      ];
      // Get the video image
      if (isset($variables['element']['#object'])) {
        /** @var \Drupal\block_content\Entity\BlockContent $parent */
        $parent = $variables['element']['#object'];
        $variables['items'][0]['video_image'] = $parent->field_video_image->view([
          'label' => 'hidden',
          'settings' => [
            'image_style' => 'video_thumb'
          ]
        ]);
      }
    }
  }
}
